### ISSUE TITLE
Add a documentation for contributing

### ISSUE THREAD

**Issue by pickfire** [riseupnet/riseup_help#225]
I wanted to contribute to the help but I doesn't know it at first, until I read each page. I hope that the help show ways to contribute to the help page.

**Comment by elijh** [comment]
hmm... i am not sure what you are suggesting. currently, there is a link at the bottom of every page that directs people to https://github.com/riseupnet/riseup_help

are you suggesting that (a) the contribute link should be more prominent? or (b) where it links to should be more clear? or (c) something else entirely?

**Comment by pickfire** [comment]
> hmm... i am not sure what you are suggesting. currently, there is a link at the bottom of every page that directs people to https://github.com/riseupnet/riseup_help

After reading so much pages, I did not notice that line. I only notice the last line which is
```
     Support Riseup System Status Mailing Lists Email About Us Privacy Policy 
```

I think that the link should be put with the others link to let others understand that it is a link. I did not saw that link because it is a bit long and I did not notice that it is a link.

**Comment by pickfire** [comment]
Maybe try to follow http://docs.writethedocs.org/writing/beginners-guide-to-docs/#id1 for **README.md** and move the others to **CONTRIBUTING.md** to provide a clear info for editing the riseup help in **README.md**. And is there a mailing list for the help or irc chat or jabber chat for riseup help?

**Comment by baldurmen** [comment]
@pickfire Hmm, old issue, but riseup's IRC channel is #riseup on irc.indymedia.org. AFAIK there is not help list, but if you are looking to help with translation there is a translation list. You can find all the infos here: https://we.riseup.net/riseup+translation

I do not agree with you on the README.md issue though. Since the whole README explains how to contribute, I don't see the point nor how it would be divided.

**Comment by pickfire** [comment]
Well, I think README is enough, I should close this issue.
