### ISSUE TITLE
Add I2P to network security

### ISSUE THREAD

**Issue by pickfire** [riseupnet/riseup_help#232]
Add [I2P](geti2p.net) to network security.

**Comment by kradan** [comment]
@pickfire, can you please provide a short paragraph to be added?

**Comment by pickfire** [comment]
@kradan I haven't tried i2p yet, I have no idea what to add, I only know that you need to provide you act as a node unlike tor.

**Comment by jmfgdev** [comment]
I think i2p is like a peer encrypted layered meteorite network,  both different and similar to TOR at the same time.

**Comment by kradan** [comment]
interesting, although I no clue yet why it should appear in Riseup's help pages.

**Comment by wh1t3fang** [comment]
It is an alternative to Tor that can be used for UDP connections so it can run a wider variety of applications.  Although it is not as well known or thoroughly audited as Tor, it is likely to grow more than other alternatives to Tor.  Nearly all peers in I2p participate in routing for other peers so the more users, the more routers participating in the network.

**Comment by sqil2019** [comment]
I think this issue should be closed - at the moment there is no suggested text to put into the pages, and i2p is not currently a safe recommendation. I dont say this because I know something is wrong with i2p, or that i2p is bad... I just do not think it is a good idea to recommend a technology that isn't as robust or as well audited as tor.

**Comment by baldurmen** [comment]
@micah I think this issue should be closed.
