### ISSUE TITLE
Where is the proof of new riseup service and v3 onion?

### ISSUE THREAD

**Issue by m7268900062** [riseupnet/riseup_help#459]
Riseup: http://vww6ybal4bd7szmgncyruucpgfkqahzddi37ktceo3ah7ngmcopnpyyd.onion
searx.riseup.net: http://ozmh2zkwx5cjuzopui64csb5ertcooi5vya6c2gm4e3vcvf2c2qvjiyd.onion

Found these on Tor blog. Where is the proof of these? I can't find it on your "security -  tor" webpage.
Please confirm that these are your onions, and "searx.riseup.net" is your service.

**Comment by m7268900062** [comment]
And add your service to wiki.
https://github.com/asciimoo/searx/issues/1060

**Comment by kradan** [comment]
Since ef4d6638bdb1b18d2aa58b2838cc7bc0a56b42bd vww6ybal4bd7szmgncyruucpgfkqahzddi37ktceo3ah7ngmcopnpyyd.onion is [officially signed](http://vww6ybal4bd7szmgncyruucpgfkqahzddi37ktceo3ah7ngmcopnpyyd.onion/en/security/network-security/tor#riseups-tor-hidden-services). The metasearch is not yet documented in the help pages yet. It may be worth adding to a new page under network security. Would you like to write a draft?

**Comment by disturbio** [comment]
searx is not an official service we provide, but an instance some birds run. we are not going to add it to our documentation for now.
