### ISSUE TITLE
Framasoft shouldn't be displayed in the list of radical servers

### ISSUE THREAD

**Issue by smonff** [riseupnet/riseup_help#514]
Framasoft does a great job in the domain of education about free software and the fight against major internet corporations. Thought, I don't think they should appear in [a list](https://riseup.net/fr/security/resources/radical-servers) of "anti-hierarchy, autonomous revolutionary collectives which provide free or mutual aid services to radical and grassroots activists". This is just not what they are and it is an error to define them as so in this list.

I post this to open a talk about it and will provide a PR if it is accepted.

**Comment by kradan** [comment]
As no one objected so far I'll commit a change to apply this during the next days.

**Comment by elijh** [comment]
The entry was added by Framasoft themselves, so I am inclined to keep it. I think it would be better to simply expand the definition to include "autonomous, feminist, or radical server projects".

Under this definition, we could include many awesome projects not included, such as systerserver, greennet, codigosur, colnodo, pangea, guifinet, and others.

**Comment by kradan** [comment]
I like the idea very much. Shall we brainstorm a bit more in here and I'll create PR from that?

- [Syster Server](https://systerserver.net/) offers services to feminist, queer and antipatriarchal groups and collectives. The syster server is run by women, using free software only. It acts as a place to learn system administration skills, host services and inspire others to do the same. Services: [git](https://git.systerserver.net), [eclectictechcarnival.org](https://eclectictechcarnival.org/ETC/about/index.html), ask :)
- [GreeNet](http://www.greennet.net/) is a Internet Service Provider (ISP) located in the Boston metropolitan area offering services to individuals, businesses, organizations and other ISPs throughout the USA and the world. specialized in eCommerce servers (hosting and development) and VoIP telephony. Services: Email, Hosting, ...
- [Codigosur](https://codigosur.org/ ) is a collective of activists from different social movements in Latin America for collaboration and the development of communication tools, culture and free technology
Services: Email, Hosting, Lists, Mumble, Streaming, TLS, Etherpad, DNS and more
  - [Association for Progressive Communication](https://www.apc.org/) [Projects](https://www.apc.org/en/our-work/current-projects)
- [Colnodo](https://colnodo.apc.org/es/servicios) is a Colombian non-profit organization that aims to facilitate communication and the exchange of information, experience, and expertise between Colombian organizations through low-cost electronic networks. https://cyberstewards.org/category/colnodo/ 
  - Linda Patiño from Colnodo aims for the development of digital strategies to reach and engage with key audiences, including women, youth, and social activists. Together with the Take Back the Tech campaign in Colombia she developed a social media strategy to support an intense 16 days of activism.
  - [Take Back The Tech](https://en.wikipedia.org/wiki/Take_Back_The_Tech!) is a global campaign that connects the issue of violence against women and information and communications technology (ICT). It aims to raise awareness on the way violence against women is occurring on ICT platforms such as the Internet and mobile phones, and to call for people to use ICT in activism to end violence against women. It was initiated by the [Association for Progressive Communications](https://en.wikipedia.org/wiki/Association_for_Progressive_Communications), Women's Networking Support Programme, in 2006. Since then, the campaign has been taken up and organised by individuals, collectives and non-governmental organizations in at least 24 countries
- [Gleducar](http://www.gleducar.org.ar/) is a free educational project emerged in Argentina in 2002. It is also an important NGO (Civil Association) from Argentina in the field of education and technology.
Gleducar is an independent community composed of teachers, students and education activists linked by a common interest in collective work, cooperative knowledge building and free distribution of knowledge. The project works around different themes, such as Open Education, Open Access, Free Knowledge, Popular Education, peer education, collaborative learning and Free Technologies, and promotes the use of Free Software in schools as a pedagogical and technical system, with the objective of changing the paradigm of production, construction and dissemination of educational content.  https://en.wikipedia.org/wiki/Gleducar
- Available on iPhone, Android and Web, [Pangea](https://www.pangea.com/company/about.html) is a new social network that allows users to easily choose what they share with friends, close friends, family, colleagues or the whole world. 
- [Guifi.net](https://guifi.net/en) is a free, open and neutral, mostly wireless telecommunications community network" around Catalonia and Valencia in Spain. The nodes of the network are contributed by individuals, companies and administrations that freely connect to an open network of telecommunications and extend the network wherever the infrastructure and content might not otherwise be accessible. https://en.wikipedia.org/wiki/Guifi.net
- [Telecentre](https://en.wikipedia.org/wiki/Telecentre) is a widely adopted concept to provide free services at a pulic space. [Howto](https://en.wikibooks.org/wiki/A_Guidebook_for_Managing_Telecentre_Networks)
