### ISSUE TITLE
Moving section of donate page

### ISSUE THREAD

**Issue by brennaw** [riseupnet/riseup_help#652]
https://riseup.net/en/about-us/donate @taggart 

Put at the top of page:
 Support radical alternatives!
    Suggested contribution

Then the table of contents

    Donate by mail
    Donate by credit card
        Paypal
    Donate cryptocurrency
        Bitcoin
        Zcash
        Monero
        FairCoin
        BCash
    Donate by IBAN transfer
MOVE TO TOP **Support radical alternatives!
  MOVE TO TOP  Suggested contribution**
    Frequently Asked Questions
        Why do you only accept bank transfers in EUR?
        How do I donate in currencies other than USD or EUR?
        How do I donate anonymously?
        How do I cancel recurring payments?

**Comment by taggart** [comment]
I started to look into this and realized that the page _used_ to be that way and @micah had rearranged things the way they are after complaints from some users. See this commit https://github.com/riseupnet/riseup_help/commit/8a3443c5243a973ded7a4fc665a800086fa8fb05

What brenna and I talked about was two things:

1. The need for a "campaign" page for the upcoming fundraiser that we can easily link to. This has always been the donate page in the past, but we felt it should have some background at the top (since things like banners at the top of services won't say much).
2. The people that micah mentioned complaining in the above commit probably already knew who riseup was and wanted to donate. But for people new to riseup, the "support radical alternatives" section is probably more important to be seen first.

So how can we structure things in a way to meet these goals? Maybe a separate campaign page?

**Comment by micah** [comment]
I think the idea of having a separate campaign page makes sense and would address all of these issues.

**Comment by taggart** [comment]
I have an idea of how to solve this with the donate page:

* drop the TOC, it's consuming too much real estate at the top of the page
* move section 5 to the top
* add a button/link "I'm ready to donate" to quickly take you to the section of the page where you can do so

**Comment by taggart** [comment]
I opened PR #660 to solve this.

**Comment by taggart** [comment]
I had to do a new PR #661

**Comment by taggart** [comment]
This got merged, closing.
