### ISSUE TITLE
Riseupis down?!

### ISSUE THREAD

**Issue by RainerBielefeld** [riseupnet/riseup_help#762]
Well, not a real help issue, but [riseup.net](https://www.riseup.net/) seemsto be [down](https://downforeveryoneorjustme.com/riseup.net)?
https://riseupstatus.net/ tells nothing about this problem.

**Comment by wunewww** [comment]
Yes, it seems to be down just hours ago, now it works again.

**Comment by disturbio** [comment]
We were subject to a DDoS attack last night which couldn't be controlled by our mitigations. I'm unsure why riseupstatus.net wasn't updated thought, I will ask

**Comment by disturbio** [comment]
Ok, the reason is that while this was happening there was also a blackout in some places of seattle that didn't help much to resolve the situation with the attack or do any kind of work online. Just bad luck to deal with awful people.

I'm closing this bug since it's not actually a bug. Have a good day.

**Comment by RainerBielefeld** [comment]
Thx for info and repairing the problem!
